import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";


export function hasEnvVars(...vars: string[]): boolean {
  return vars.every((v) => !!process.env[v])
}


export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// English to Urdu translation dictionary
export const englishToUrdu: { [key: string]: string } = {
  // Common words for blog summarization

   "a": "ایک",
  "ability": "صلاحیت",
  "about": "کے بارے میں",
  "above": "اوپر",
  "accept": "قبول کرنا",
  "according": "کے مطابق",
  "account": "اکاؤنٹ",
  "across": "پار",
  "act": "عمل",
  "action": "عمل",
  "activity": "سرگرمی",
  "actually": "دراصل",
  "add": "شامل کرنا",
  "address": "پتہ",
  "administration": "انتظامیہ",
  "admit": "تسلیم کرنا",
  "adult": "بالغ",
  "affect": "متاثر کرنا",
  "after": "کے بعد",
  "again": "دوبارہ",
  "against": "کے خلاف",
  "age": "عمر",
  "agency": "ایجنسی",
  "agent": "ایجنٹ",
  "ago": "پہلے",
  "agree": "متفق ہونا",
  "agreement": "معاہدہ",
  "ahead": "آگے",
  "air": "ہوا",
  "all": "تمام",
  "allow": "اجازت دینا",
  "almost": "تقریباً",
  "alone": "تنہا",
  "along": "ساتھ",
  "already": "پہلے ہی",
  "also": "بھی",
  "although": "اگرچہ",
  "always": "ہمیشہ",
  "amazing": "حیرت انگیز",
  "amount": "مقدار",
  "analysis": "تجزیہ",
  "ancient": "قدیم",
  "and": "اور",
  "animal": "جانور",
  "another": "ایک اور",
  "answer": "جواب",
  "any": "کوئی",
  "anyone": "کوئی بھی",
  "anything": "کچھ بھی",
  "appear": "نظر آنا",
  "apply": "درخواست دینا",
  "approach": "رویہ",
  "appropriate": "مناسب",
  "area": "علاقہ",
  "argue": "بحث کرنا",
  "arm": "بازو",
  "around": "ارد گرد",
  "art": "فَن",
  "article": "مضمون",
  "artist": "آرٹسٹ",
  "as": "جیسا کہ",
  "ask": "پوچھنا",
  "assume": "فرض کرنا",
  "at": "پر",
  "attack": "حملہ",
  "attention": "توجہ",
  "author": "مصنف",
  "authority": "اختیار",
  "available": "دستیاب",
  "avoid": "بچنا",
  "away": "دور",
  "baby": "بچہ",
  "back": "پیچھے",
  "bad": "بُرا",
  "balance": "توازن",
  "ball": "گیند",
  "bank": "بینک",
  "bar": "بار",
  "base": "بنیاد",
  "beautiful": "خوبصورت",
  "because": "کیونکہ",
  "become": "بننا",
  "bed": "بستر",
  "before": "پہلے",
  "begin": "شروع کرنا",
  "behavior": "رویے",
  "behind": "پیچھے",
  "believe": "یقین کرنا",
  "below": "نیچے",
  "benefit": "فائدہ",
  "best": "بہترین",
  "better": "بہتر",
  "between": "کے درمیان",
  "beyond": "سے باہر",
  "big": "بڑا",
  "bill": "بِل",
  "billion": "ارب",
  "bit": "تھوڑا",
  "black": "کالا",
  "blood": "خون",
  "blue": "نیلا",
  "board": "بورڈ",
  "body": "جسم",
  "book": "کتاب",
  "both": "دونوں",
  "box": "ڈبہ",
  "boy": "لڑکا",
  "break": "توڑنا",
  "bring": "لانا",
  "brother": "بھائی",
  "build": "تعمیر کرنا",
  "building": "عمارت",
  "business": "کاروبار",
  "but": "لیکن",
  "buy": "خریدنا",
  "by": "کی طرف سے",
  "call": "بلانا",
  "camera": "کیمرہ",
  "campaign": "مہم",
  "can": "سکتا ہے",
  "cancer": "کینسر",
  "candidate": "امیدوار",
  "capital": "دارالحکومت",
  "car": "گاڑی",
  "card": "کارڈ",
  "care": "خیال",
  "career": "کیریئر",
  "carry": "لے جانا",
  "case": "کیس",
  "catch": "پکڑنا",
  "cause": "وجہ",
  "celebrate": "جشن منانا",
  "center": "مرکز",
  "central": "مرکزی",
  "century": "صدی",
  "certain": "یقینی",
  "certainly": "یقینی طور پر",
  "chair": "کرسی",
  "challenge": "چیلنج",
  "chance": "موقع",
  "change": "تبدیلی",
  "character": "کردار",
  "charge": "چارج",
  "check": "چیک کرنا",
  "child": "بچہ",
  "choice": "انتخاب",
  "choose": "منتخب کرنا",
  "church": "چرچ",
  "city": "شہر",
  "claim": "دعویٰ کرنا",
  "class": "کلاس",
  "clear": "صاف",
  "clearly": "واضح طور پر",
  "close": "بند",
  "coach": "کوچ",
  "cold": "ٹھنڈا",
  "collection": "مجموعہ",
  "college": "کالج",
  "color": "رنگ",
  "come": "آنا",
  "commercial": "تجارتی",
  "common": "عام",
  "community": "کمیونٹی",
  "company": "کمپنی",
  "compare": "موازنہ کرنا",
  "computer": "کمپیوٹر",
  "concern": "تشویش",
  "condition": "حالت",
  "conference": "کانفرنس",
  "consider": "غور کرنا",
  "consumer": "صارف",
  "contain": "شامل کرنا",
  "content": "مواد",
  "continue": "جاری رکھنا",
  "control": "کنٹرول",
  "cost": "لاگت",
  "country": "ملک",
  "couple": "جوڑا",
  "course": "کورس",
  "court": "عدالت",
  "cover": "ڈھکنا",
  "create": "بنانا",
  "crime": "جرم",
  "cultural": "ثقافتی",
  "culture": "ثقافت",
  "current": "موجودہ",
  "customer": "گاہک",
  "cut": "کاٹنا",
  "dark": "تاریک",
  "data": "ڈیٹا",
  "daughter": "بیٹی",
  "day": "دن",
  "dead": "مُردہ",
  "deal": "سودا",
  "death": "موت",
  "debate": "بحث",
  "decade": "دہائی",
  "decide": "فیصلہ کرنا",
  "decision": "فیصلہ",
  "deep": "گہرا",
  "defense": "دفاع",
  "degree": "ڈگری",
  "democratic": "جمہوری",
  "describe": "بیان کرنا",
  "design": "ڈیزائن",
  "despite": "اس کے باوجود",
  "determine": "تعین کرنا",
  "develop": "ترقی دینا",
  "development": "ترقی",
  "die": "مرنا",
  "difference": "فرق",
  "different": "مختلف",
  "difficult": "مشکل",
  "direction": "سمت",
  "director": "ڈائریکٹر",
  "discover": "دریافت کرنا",
  "discussion": "گفتگو",
  "disease": "بیماری",
  "do": "کرنا",
  "doctor": "ڈاکٹر",
  "dog": "کتا",
  "door": "دروازہ",
  "down": "نیچے",
  "draw": "کھینچنا",
  "dream": "خواب",
  "drive": "چلانا",
  "drop": "گرنا",
  "drug": "دوا",
  "during": "کے دوران",
  "each": "ہر ایک",
  "early": "جلدی",
  "east": "مشرق",
  "easy": "آسان",
  "eat": "کھانا",
  "economic": "معاشی",
  "economy": "معیشت",
  "edge": "کنارہ",
  "education": "تعلیم",
  "effect": "اثر",
  "effort": "کوشش",
  "eight": "آٹھ",
  "either": "یا تو",
  "election": "انتخاب",
  "else": "دوسرا",
  "employee": "ملازم",
  "end": "اختتام",
  "energy": "توانائی",
  "enjoy": "لطف اٹھانا",
  "enough": "کافی",
  "enter": "داخل ہونا",
  "entire": "پورا",
  "environment": "ماحول",
  "especially": "خاص طور پر",
  "establish": "قائم کرنا",
  "even": "بھی",
  "evening": "شام",
  "event": "واقعہ",
  "ever": "کبھی",
  "every": "ہر",
  "everybody": "ہر کوئی",
  "everyone": "ہر کوئی",
  "everything": "ہر چیز",
  "evidence": "ثبوت",
  "exactly": "بالکل",
  "example": "مثال",
  "exist": "موجود ہونا",
  "expect": "توقع کرنا",
  "experience": "تجربہ",
  "expert": "ماہر",
  "explain": "وضاحت کرنا",
  "eye": "آنکھ",
  "face": "چہرہ",
  "factor": "عنصر",
  "fail": "ناکام ہونا",
  "fair": "منصفانہ",
  "fall": "گرنا",
  "family": "خاندان",
  "far": "دور",
  "fast": "تیز",
  "father": "والد",
  "fear": "خوف",
  "federal": "وفاقی",
  "feel": "محسوس کرنا",
  "feeling": "احساس",
  "few": "چند",
  "field": "میدان",
  "fight": "لڑنا",
  "figure": "شکل",
  "fill": "بھرنا",
  "final": "حتمی",
  "finally": "آخرکار",
  "financial": "مالیاتی",
  "find": "تلاش کرنا",
  "fine": "ٹھیک",
  "finger": "انگلی",
  "finish": "ختم کرنا",
  "fire": "آگ",
  "firm": "مضبوط",
  "first": "پہلا",
  "fish": "مچھلی",
  "five": "پانچ",
  "floor": "فرش",
  "fly": "اڑنا",
  "focus": "توجہ",
  "follow": "پیروی کرنا",
  "food": "کھانا",
  "foot": "پاؤں",
  "for": "کے لیے",
  "force": "طاقت",
  "foreign": "غیر ملکی",
  "forget": "بھول جانا",
  "form": "شکل",
  "former": "سابقہ",
  "forward": "آگے",
  "four": "چار",
  "free": "آزاد",
  "friend": "دوست",
  "from": "سے",
  "front": "سامنے",
  "full": "بھرا ہوا",
  "fund": "فنڈ",
  "future": "مستقبل",
  "game": "کھیل",
  "garden": "باغ",
  "gas": "گیس",
  "general": "عام",
  "generally": "عام طور پر",
  "get": "حاصل کرنا",
  "girl": "لڑکی",
  "give": "دینا",
  "glass": "گلاس",
  "go": "جانا",
  "goal": "مقصد",
  "good": "اچھا",
  "government": "حکومت",
  "great": "عظیم",
  "green": "سبز",
  "ground": "زمین",
  "group": "گروپ",
  "grow": "بڑھنا",
  "growth": "افزائش",
  "guess": "اندازہ لگانا",
  "guy": "شخص",
  "hair": "بال",
  "half": "آدھا",
  "hand": "ہاتھ",
  "hang": "لٹکانا",
  "happen": "ہونا",
  "happy": "خوش",
  "hard": "سخت",
  "have": "رکھنا",
  "he": "وہ",
  "head": "سر",
  "health": "صحت",
  "hear": "سننا",
  "heart": "دل",
  "heavy": "بھاری",
  "help": "مدد",
  "her": "اس کا",
  "here": "یہاں",
  "herself": "خود",
  "high": "اونچا",
  "him": "اس کو",
  "himself": "خود",
  "his": "اس کا",
  "history": "تاریخ",
  "hit": "مارنا",
  "hold": "پکڑنا",
  "home": "گھر",
  "hope": "امید",
  "hospital": "ہسپتال",
  "hot": "گرم",
  "hotel": "ہوٹل",
  "hour": "گھنٹہ",
  "house": "گھر",
  "how": "کیسے",
  "however": "تاہم",
  "huge": "بہت بڑا",
  "human": "انسانی",
  "hundred": "سو",
  "husband": "شوہر",
  "i": "میں",
  "idea": "خیال",
  "identify": "پہچاننا",
  "if": "اگر",
  "image": "تصویر",
  "imagine": "تصور کرنا",
  "impact": "اثر",
  "important": "اہم",
  "improve": "بہتر بنانا",
  "in": "میں",
  "include": "شامل کرنا",
  "including": "بشمول",
  "income": "آمدنی",
  "increase": "اضافہ",
  "indeed": "واقعی",
  "indicate": "اشارہ کرنا",
  "individual": "انفرادی",
  "industry": "صنعت",
  "information": "معلومات",
  "inside": "اندر",
  "instead": "بجائے",
  "institution": "ادارہ",
  "interest": "دلچسپی",
  "international": "بین الاقوامی",
  "into": "میں",
  "introduce": "متعارف کرانا",
  "invest": "سرمایہ کاری کرنا",
  "involve": "شامل کرنا",
  "it": "یہ",
  "its": "اس کا",
  "itself": "خود",
  "job": "نوکری",
  "join": "شامل ہونا",
  "just": "صرف",
  "keep": "رکھنا",
  "key": "چابی",
  "kid": "بچہ",
  "kill": "مارنا",
  "kind": "قسم",
  "king": "بادشاہ",
  "knowledge": "علم",
  "land": "زمین",
  "language": "زبان",
  "large": "بڑا",
  "last": "آخری",
  "late": "دیر سے",
  "later": "بعد میں",
  "laugh": "ہنسنا",
  "law": "قانون",
  "lawyer": "وکیل",
  "lay": "لیٹنا",
  "leader": "قائد",
  "lead": "رہنمائی کرنا",
  "learn": "سیکھنا",
  "least": "کم از کم",
  "leave": "چھوڑنا",
  "left": "بائیں",
  "leg": "ٹانگ",
  "legal": "قانونی",
  "less": "کم",
  "let": "اجازت دینا",
  "letter": "خط",
  "level": "سطح",
  "lie": "جھوٹ بولنا",
  "life": "زندگی",
  "light": "روشنی",
  "like": "پسند کرنا",
  "likely": "امکانی",
  "line": "لائن",
  "list": "فہرست",
  "listen": "سننا",
  "little": "چھوٹا",
  "live": "رہنا",
  "local": "مقامی",
  "long": "لمبا",
  "look": "دیکھنا",
  "lose": "کھونا",
  "loss": "نقصان",
  "lot": "بہت",
  "love": "محبت",
  "low": "کم",
  "machine": "مشین",
  "magazine": "میگزین",
  "main": "اہم",
  "maintain": "برقرار رکھنا",
  "major": "اہم",
  "make": "بنانا",
  "man": "آدمی",
  "manage": "انتظام کرنا",
  "management": "انتظام",
  "manager": "مینیجر",
  "many": "بہت سے",
  "market": "مارکیٹ",
  "material": "مواد",
  "matter": "معاملہ",
  "maybe": "شاید",
  "me": "مجھے",
  "mean": "مطلب",
  "meaning": "مطلب",
  "measure": "پیمائش",
  "media": "میڈیا",
  "medical": "طبی",
  "meet": "ملنا",
  "meeting": "میٹنگ",
  "member": "رکن",
  "memory": "یادداشت",
  "mention": "ذکر کرنا",
  "message": "پیغام",
  "method": "طریقہ",
  "middle": "درمیان",
  "might": "شاید",
  "military": "فوجی",
  "million": "ملین",
  "mind": "دماغ",
  "minute": "منٹ",
  "miss": "یاد کرنا",
  "mission": "مشن",
  "model": "ماڈل",
  "modern": "جدید",
  "moment": "لمحہ",
  "money": "پیسہ",
  "month": "مہینہ",
  "more": "زیادہ",
  "morning": "صبح",
  "most": "سب سے زیادہ",
  "mother": "ماں",
  "move": "حرکت کرنا",
  "movement": "تحریک",
  "movie": "فلم",
  "much": "بہت",
  "music": "موسیقی",
  "must": "ضرور",
  "my": "میرا",
  "name": "نام",
  "national": "قومی",
  "natural": "قدرتی",
  "nature": "فطرت",
  "near": "قریب",
  "nearly": "تقریباً",
  "necessary": "ضروری",
  "need": "ضرورت",
  "network": "نیٹ ورک",
  "never": "کبھی نہیں",
  "new": "نیا",
  "news": "خبریں",
  "next": "اگلا",
  "nice": "اچھا",
  "night": "رات",
  "no": "نہیں",
  "none": "کوئی نہیں",
  "north": "شمال",
  "not": "نہیں",
  "note": "نوٹ",
  "nothing": "کچھ نہیں",
  "now": "اب",
  "number": "تعداد",
  "occur": "واقع ہونا",
  "of": "کا",
  "off": "بند",
  "offer": "پیشکش",
  "office": "دفتر",
  "often": "اکثر",
  "oh": "اوہ",
  "old": "پرانا",
  "on": "پر",
  "once": "ایک بار",
  "one": "ایک",
  "only": "صرف",
  "onto": "پر",
  "open": "کھلا",
  "operation": "آپریشن",
  "opportunity": "موقع",
  "option": "آپشن",
  "or": "یا",
  "order": "حکم",
  "organization": "تنظیم",
  "other": "دوسرا",
  "otherwise": "ورنہ",
  "our": "ہمارا",
  "out": "باہر",
  "outside": "باہر",
  "over": "اوپر",
  "own": "اپنا",
  "owner": "مالک",
  "page": "صفحہ",
  "pain": "درد",
  "paint": "پینٹ",
  "paper": "کاغذ",
  "parent": "والدین",
  "part": "حصہ",
  "particular": "خاص",
  "particularly": "خاص طور پر",
  "party": "پارٹی",
  "pass": "گزرنا",
  "past": "ماضی",
  "patient": "مریض",
  "pattern": "نمونہ",
  "pay": "ادائیگی",
  "people": "لوگ",
  "per": "فی",
  "perform": "کارکردگی دکھانا",
  "performance": "کارکردگی",
  "perhaps": "شاید",
  "period": "مدت",
  "person": "شخص",
  "personal": "ذاتی",
  "phone": "فون",
  "physical": "جسمانی",
  "pick": "چننا",
  "picture": "تصویر",
  "piece": "ٹکڑا",
  "place": "جگہ",
  "plan": "منصوبہ",
  "plant": "پودا",
  "play": "کھیلنا",
  "player": "کھلاڑی",
  "point": "نقطہ",
  "police": "پولیس",
  "policy": "پالیسی",
  "political": "سیاسی",
  "politics": "سیاست",
  "poor": "غریب",
  "popular": "مقبول",
  "population": "آبادی",
  "position": "پوزیشن",
  "positive": "مثبت",
  "possible": "ممکن",
  "power": "طاقت",
  "practice": "مشق",
  "prepare": "تیار کرنا",
  "present": "موجود",
  "president": "صدر",
  "pressure": "دباؤ",
  "pretty": "خوبصورت",
  "prevent": "روکنا",
  "price": "قیمت",
  "private": "نجی",
  "probably": "شاید",
  "problem": "مسئلہ",
  "process": "عمل",
  "produce": "پیدا کرنا",
  "product": "مصنوعات",
  "production": "پیداوار",
  "professional": "پیشہ ور",
  "professor": "پروفیسر",
  "program": "پروگرام",
  "project": "منصوبہ",
  "property": "جائیداد",
  "protect": "حفاظت کرنا",
  "prove": "ثابت کرنا",
  "provide": "فراہم کرنا",
  "public": "عوامی",
  "pull": "کھینچنا",
  "purpose": "مقصد",
  "push": "دھکیلنا",
  "put": "رکھنا",
  "quality": "معیار",
  "question": "سوال",
  "quickly": "تیزی سے",
  "quite": "کافی",
  "race": "نسل",
  "radio": "ریڈیو",
  "raise": "اٹھانا",
  "range": "رینج",
  "rate": "شرح",
  "rather": "بلکہ",
  "reach": "پہنچنا",
  "read": "پڑھنا",
  "ready": "تیار",
  "real": "حقیقی",
  "really": "واقعی",
  "reason": "وجہ",
  "receive": "وصول کرنا",
  "recent": "حالیہ",
  "recently": "حال ہی میں",
  "recognize": "پہچاننا",
  "record": "ریکارڈ",
  "red": "سرخ",
  "reduce": "کم کرنا",
  "reflect": "عکس ڈالنا",
  "region": "علاقہ",
  "relate": "متعلق ہونا",
  "relationship": "تعلق",
  "religious": "مذہبی",
  "remain": "باقی رہنا",
  "remember": "یاد رکھنا",
  "remove": "ہٹانا",
  "report": "رپورٹ",
  "represent": "نمائندگی کرنا",
  "research": "تحقیق",
  "resource": "وسیلہ",
  "respond": "جواب دینا",
  "response": "جواب",
  "rest": "آرام",
  "result": "نتیجہ",
  "return": "واپس آنا",
  "reveal": "ظاہر کرنا",
  "rich": "امیر",
  "right": "صحیح",
  "risk": "خطرہ",
  "road": "سڑک",
  "rock": "چٹان",
  "role": "کردار",
  "room": "کمرہ",
  "rule": "قاعدہ",
  "run": "دوڑنا",
  "safe": "محفوظ",
  "same": "ایک ہی",
  "save": "بچانا",
  "say": "کہنا",
  "scene": "منظر",
  "school": "سکول",
  "science": "سائنس",
  "scientist": "سائنس دان",
  "score": "سکور",
  "sea": "سمندر",
  "season": "موسم",
  "seat": "نشست",
  "second": "دوسرا",
  "secret": "راز",
  "security": "سیکیورٹی",
  "see": "دیکھنا",
  "seek": "تلاش کرنا",
  "seem": "لگنا",
  "sell": "بیچنا",
  "send": "بھیجنا",
  "senior": "سینئر",
  "sense": "احساس",
  "series": "سیریز",
  "serious": "سنجیدہ",
  "serve": "خدمت کرنا",
  "service": "سروس",
  "set": "سیٹ",
  "seven": "سات",
  "several": "کئی",
  "sex": "جنس",
  "shake": "ہلانا",
  "share": "شیئر کرنا",
  "she": "وہ",
  "ship": "جہاز",
  "shirt": "شرٹ",
  "shoot": "گولی مارنا",
  "short": "مختصر",
  "should": "چاہیے",
  "shoulder": "کندھا",
  "show": "دکھانا",
  "side": "طرف",
  "sign": "علامت",
  "significant": "اہم",
  "similar": "ملتا جلتا",
  "simple": "سادہ",
  "simply": "صرف",
  "since": "جب سے",
  "sing": "گانا",
  "single": "اکیلا",
  "sister": "بہن",
  "sit": "بیٹھنا",
  "site": "سائٹ",
  "situation": "صورتحال",
  "six": "چھ",
  "size": "سائز",
  "skill": "ہنر",
  "skin": "جلد",
  "small": "چھوٹا",
  "smile": "مسکرانا",
  "so": "تو",
  "social": "سماجی",
  "society": "معاشرہ",
  "some": "کچھ",
  "somebody": "کوئی",
  "someone": "کوئی",
  "something": "کچھ",
  "sometimes": "کبھی کبھی",
  "son": "بیٹا",
  "song": "گانا",
  "soon": "جلد",
  "sort": "قسم",
  "sound": "آواز",
  "source": "ماخذ",
  "south": "جنوب",
  "space": "جگہ",
  "speak": "بولنا",
  "special": "خاص",
  "specific": "مخصوص",
  "speech": "تقریر",
  "spend": "خرچ کرنا",
  "sport": "کھیل",
  "spring": "بہار",
  "staff": "عملہ",
  "stage": "مرحلہ",
  "stand": "کھڑے ہونا",
  "standard": "معیاری",
  "start": "شروع کرنا",
  "state": "ریاست",
  "statement": "بیان",
  "station": "اسٹیشن",
  "stay": "رہنا",
  "step": "قدم",
  "still": "ابھی بھی",
  "stock": "اسٹاک",
  "stop": "رکنا",
  "store": "دکان",
  "story": "کہانی",
  "strategy": "حکمت عملی",
  "street": "گلی",
  "strong": "مضبوط",
  "structure": "ساخت",
  "student": "طالب علم",
  "study": "مطالعہ",
  "stuff": "چیزیں",
  "style": "انداز",
  "subject": "موضوع",
  "success": "کامیابی",
  "successful": "کامیاب",
  "such": "ایسا",
  "suddenly": "اچانک",
  "suffer": "تکلیف اٹھانا",
  "suggest": "تجویز کرنا",
  "suit": "سوٹ",
  "summer": "گرمی",
  "sun": "سورج",
  "support": "مدد",
  "sure": "یقینی",
  "surface": "سطح",
  "system": "نظام",
  "table": "میز",
  "take": "لینا",
  "talk": "بات کرنا",
  "task": "کام",
  "tax": "ٹیکس",
  "teach": "سکھانا",
  "teacher": "استاد",
  "team": "ٹیم",
  "technology": "ٹیکنالوجی",
  "tell": "بتانا",
  "ten": "دس",
  "tend": "جھکاؤ",
  "term": "اصطلاح",
  "test": "ٹیسٹ",
  "than": "سے",
  "thank": "شکریہ",
  "that": "وہ",
  "the": "یہ",
  "their": "ان کا",
  "them": "ان کو",
  "themselves": "خود",
  "then": "پھر",
  "theory": "نظریہ",
  "there": "وہاں",
  "these": "یہ",
  "they": "وہ",
  "thing": "چیز",
  "think": "سوچنا",
  "third": "تیسرا",
  "this": "یہ",
  "those": "وہ",
  "though": "اگرچہ",
  "thought": "سوچ",
  "thousand": "ہزار",
  "threat": "خطرہ",
  "three": "تین",
  "through": "کے ذریعے",
  "throughout": "بھر میں",
  "throw": "پھینکنا",
  "thus": "اس طرح",
  "time": "وقت",
  "to": "کو",
  "today": "آج",
  "together": "ایک ساتھ",
  "too": "بھی",
  "top": "اوپر",
  "total": "کل",
  "toward": "کی طرف",
  "town": "قصبہ",
  "trade": "تجارت",
  "traditional": "روایتی",
  "training": "تربیت",
  "travel": "سفر",
  "treat": "علاج کرنا",
  "treatment": "علاج",
  "tree": "درخت",
  "trial": "ٹرائل",
  "trip": "سفر",
  "trouble": "مسئلہ",
  "true": "سچا",
  "truth": "سچائی",
  "try": "کوشش کرنا",
  "turn": "موڑنا",
  "two": "دو",
  "type": "قسم",
  "under": "نیچے",
  "understand": "سمجھنا",
  "unit": "یونٹ",
  "until": "جب تک",
  "up": "اوپر",
  "upon": "پر",
  "us": "ہمیں",
  "use": "استعمال",
  "usually": "عام طور پر",
  "value": "قیمت",
  "various": "مختلف",
  "very": "بہت",
  "victim": "متاثرہ",
  "view": "نظارہ",
  "violence": "تشدد",
  "visit": "دورہ",
  "voice": "آواز",
  "vote": "ووٹ",
  "wait": "انتظار کرنا",
  "walk": "چلنا",
  "wall": "دیوار",
  "want": "چاہنا",
  "war": "جنگ",
  "watch": "دیکھنا",
  "water": "پانی",
  "way": "طریقہ",
  "we": "ہم",
  "weapon": "ہتھیار",
  "wear": "پہننا",
  "week": "ہفتہ",
  "weight": "وزن",
  "well": "اچھا",
  "west": "مغرب",
  "what": "کیا",
  "whatever": "جو کچھ بھی",
  "when": "جب",
  "where": "کہاں",
  "whether": "چاہے",
  "which": "کونسا",
  "while": "جبکہ",
  "white": "سفید",
  "who": "کون",
  "whole": "پورا",
  "whom": "جسے",
  "whose": "جس کا",
  "why": "کیوں",
  "wide": "چوڑا",
  "wife": "بیوی",
  "will": "گا",
  "win": "جیتنا",
  "wind": "ہوا",
  "window": "کھڑکی",
  "wish": "خواہش",
  "with": "کے ساتھ",
  "within": "کے اندر",
  "without": "کے بغیر",
  "woman": "عورت",
  "wonder": "حیرت",
  "wonderful": "شاندار",
  "word": "لفظ",
  "work": "کام",
  "worker": "مزدور",
  "world": "دنیا",
  "worry": "پریشان ہونا",
  "would": "گا",
  "write": "لکھنا",
  "writer": "مصنف",
  "wrong": "غلط",
  "yard": "گز",
  "yeah": "ہاں",
  "year": "سال",
  "yes": "ہاں",
  "yet": "ابھی تک",
  "you": "آپ",
  "young": "جوان",
  "your": "آپ کا",
  "yourself": "خود",
  "are": "ہیں",
  "was": "تھا",
  "were": "تھے",
  "be": "ہونا",
  "been": "رہا ہے",
  "has": "ہے",
  "had": "تھا",
  "could": "سکتا تھا",
  "may": "ہو سکتا ہے",
 
  
  // Technology related terms
  "software": "سافٹ ویئر",
  "hardware": "ہارڈ ویئر",
  "internet": "انٹرنیٹ",
  "website": "ویب سائٹ",
  "application": "ایپلیکیشن",
  "programming": "پروگرامنگ",
  "coding": "کوڈنگ",
  "artificial intelligence": "مصنوعی ذہانت",
  "machine learning": "مشین لرننگ",
  "algorithm": "الگورتھم",
  "database": "ڈیٹابیس",
  "server": "سرور",
  "cloud": "کلاؤڈ",
  
  // Common verbs
  "implement": "نافذ کرنا",
  "optimize": "بہتر بنانا",
  "solve": "حل کرنا",
  "fix": "ٹھیک کرنا",
  

  "user": "صارف",
  "university": "یونیورسٹی",
  "blog": "بلاگ",
  "post": "پوسٹ",
  "text": "متن",
  "english": "انگریزی",
  "urdu": "اردو",
  
  // Adjectives
 
  "minor": "چھوٹا",
  "complex": "پیچیدہ",
  "advanced": "ایڈوانس",
  "basic": "بنیادی",
  "digital": "ڈیجیٹل",
  "online": "آن لائن",
  
  "closed": "بند",
  
  "multiple": "متعدد",
  "nine": "نو",
  
  "nor": "نہ",

};

// Simple translation function
export function translateToUrdu(text: string): string {
  let translated = text.toLowerCase();
  
  // Replace English words with Urdu equivalents
  Object.entries(englishToUrdu).forEach(([english, urdu]) => {
    const regex = new RegExp(`\\b${english}\\b`, 'gi');
    translated = translated.replace(regex, urdu);
  });
  
  return translated;
}